Add reindex module and function to reindex solr from cache
pulibrary/dpul-collections pull request #101
Opened 2024-09-25 22:49 UTC by eliotjordan

Adds example function for resetting processor marker for an indexing stage and restarting the consumer.

2024-09-27 19:23 UTC, tpendragon submitted a review, later dismissed
More discussion points than specific changes.

2024-09-27 19:23 UTC, tpendragon commented on lib/dpul_collections/utilities.ex
> +  def reindex_all(cache_version) do
Do we need to reset the state of everything if want to reindex? Like if we want a full re-hydration, can't we just reset the hydrator? And if we want a full retransformation without hydration, we just reset the transformer?

2024-09-27 19:23 UTC, tpendragon commented on lib/dpul_collections/utilities.ex
> +    GenServer.stop(Figgy.TransformationConsumer)
Should we use Broadway.stop?

2024-09-27 19:23 UTC, tpendragon commented on lib/dpul_collections/utilities.ex
> +  def reindex_solr(cache_version) do
Should these functions be part of the Consumer namespace? So like, `Figgy.IndexingConsumer.Restart()` or `Reset()` or `ResetTo(nil)` or something?

2024-10-07 17:46 UTC, tpendragon commented
Update: I tried doing it this way while I was reindexing for description and it didn't work - if indexing is running, it writes the marker between me updating and restarting the node, no matter how quickly I went. I think we need to stop the producer in-band somehow.

2024-10-07 18:53 UTC, hackartisan commented
> Update: I tried doing it this way while I was reindexing for description and it didn't work - if indexing is running, it writes the marker between me updating and restarting the node, no matter how quickly I went. I think we need to stop the producer in-band somehow.

I feel like we should be able to start these broadway pipelines as named processes so that we can shut them down by referencing them with an atom instead of needing a PID

2024-10-14 20:19 UTC, hackartisan requested changes

2024-10-14 20:19 UTC, hackartisan commented on test/dpul_collections/indexing_pipeline/integration/full_integration_test.exs
> +  alias ElixirLS.LanguageServer.Providers.CodeLens.Test
Remove this?

2024-10-14 21:08 UTC, hackartisan submitted a review, later dismissed

2024-10-15 16:10 UTC, eliotjordan reviewed
Nice work. 💯

2024-10-15 16:12 UTC, merged