Proof of concept index metrics tracker.
pulibrary/dpul-collections pull request #153
Opened 2024-10-21 22:38 UTC by tpendragon

This is nowhere near complete, but it's a nice proof of concept for time to poll as defined in #115

2024-10-22 14:11 UTC, hackartisan commented
This is looking good. Do you think we shouldn't use a span, then?

2024-10-22 14:12 UTC, hackartisan commented
Like using https://hexdocs.pm/opentelemetry_api/OpenTelemetry.Tracer.html#start_span/2

2024-10-22 19:03 UTC, tpendragon commented
> Like using https://hexdocs.pm/opentelemetry_api/OpenTelemetry.Tracer.html#start_span/2

I looked at that, but I couldn't figure out how to wrap something around a process that happens over a long period of time. Like I guess I could spawn a task that spins and waits...but I think just sending an event for the duration is just as good.

2024-11-27 20:02 UTC, hackartisan requested changes
This is very good and cool, the IndexMetricsTracker genserver is a bit hard for me to follow; maybe we could look at it together and then I could make some suggestions around organization and documentation that might help me or someone looking at it in the future?

2024-11-27 20:30 UTC, tpendragon commented on lib/dpul_collections/indexing_pipeline/dashboard_page.ex
> +defmodule DpulCollections.IndexingPipeline.DashboardPage do
I put it here because it didn't really seem like it was part of the app, but happy to move it.

2024-11-27 20:31 UTC, tpendragon commented on lib/dpul_collections/indexing_pipeline/dashboard_page.ex
> +        hydration_times: IndexMetricsTracker.index_times(HydrationProducerSource),
To?

2024-11-27 21:08 UTC, hackartisan commented on lib/dpul_collections/indexing_pipeline/dashboard_page.ex
> +        hydration_times: IndexMetricsTracker.index_times(HydrationProducerSource),
what about cache_times?

2024-11-27 21:08 UTC, tpendragon commented on lib/dpul_collections/indexing_pipeline/dashboard_page.ex
> +        hydration_times: IndexMetricsTracker.index_times(HydrationProducerSource),
Oh interesting, I tried `index_durations` - it's the index part that's confusing?

2024-11-28 00:08 UTC, tpendragon commented on lib/dpul_collections/index_metrics_tracker.ex
> +  defp handle_ack_received([:database_producer, :ack, :done], _measurements, metadata, _config) do
Because I should probably call that function something different

2024-12-04 16:25 UTC, hackartisan approved these changes

2024-12-04 17:35 UTC, hackartisan approved these changes

2024-12-04 17:35 UTC, merged