Add related data to hydration cache
pulibrary/dpul-collections pull request #219
Opened 2024-11-07 20:32 UTC by tpendragon

- **Get a test written that hydrates an EphemeraFolder.**
- **Add related_data json field.**
- **Start storing some amount of related_data.**
- **Initial implementation done.**

2024-11-07 21:33 UTC, tpendragon commented on lib/dpul_collections/indexing_pipeline.ex
> +    attrs = Map.merge(%{related_data: %{}}, attrs)
I added this as a default because we have tests that don't pass related_data, I don't know that it's actually real.

2024-11-07 21:33 UTC, tpendragon commented on lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
> +  def extract_related_data(resource) do
Part of me feels like all this code should be somewhere else, but I don't really know where. Like I'm scared it's gonna get a lot bigger, but maybe it won't?

2024-11-08 14:52 UTC, hackartisan requested changes

2024-11-08 17:02 UTC, tpendragon commented on lib/dpul_collections/indexing_pipeline.ex
> +    attrs = Map.merge(%{related_data: %{}}, attrs)
The hydration_cache_entry complains that you didn't pass it.

2024-11-08 17:05 UTC, tpendragon commented on lib/dpul_collections/indexing_pipeline.ex
> +    attrs = Map.merge(%{related_data: %{}}, attrs)
Ahh, I think I can do `attrs[:related_data]` instead of `attrs.related_data` and it won't raise if it's nil

2024-11-08 18:25 UTC, tpendragon commented on lib/dpul_collections/indexing_pipeline/figgy/hydration_consumer.ex
>        when internal_resource in ["EphemeraTerm"] do
I thought about this, but I the EphemeraFolder has some open/public filters as well that didn't seem appropriate. I'd have to add something to the map, or handle the whole message in Figgy.Resource

2024-11-08 18:46 UTC, hackartisan approved these changes

2024-11-08 18:46 UTC, merged