Add test coverage measuring
pulibrary/dpul-collections pull request #40
Opened 2024-07-16 21:56 UTC by tpendragon

This adds excoveralls (which is the state of the art coverage tool) and a `mix spec` command which will run the whole suite with an HTML export of coverage.

I decided on excoveralls based on the HTML view of `mix test --cover` not having a table of contents to see all coverage in one place. Read on https://elixirforum.com/t/code-coverage-tools-for-elixir/18102 that `excoveralls` was the best option, and it seems well maintained.

Closes #37

2024-07-17 13:50 UTC, hackartisan requested changes
Looks good! I tried it, it doesn't seem to print out the coverage when you run `mix test` -- is it determined separately / statically? `mix coveralls` seems to work, but I'm not sure where to see the html view you referenced. Can you add to the readme instructions for how to run / view coverage?

2024-07-17 13:56 UTC, hackartisan commented on mix.exs
> +      test_coverage: [tool: ExCoveralls],
oh i guess this makes `mix test --cover` use excoveralls

2024-07-17 14:10 UTC, tpendragon commented
@hackartisan Mix spec or mix coveralls.html should generate the html page.

2024-07-17 20:18 UTC, hackartisan commented
@tpendragon can you add that to the readme

2024-07-17 21:11 UTC, tpendragon commented
> @tpendragon can you add that to the readme

Yup!

2024-07-18 13:10 UTC, hackartisan approved these changes

2024-07-18 13:10 UTC, merged